---

- name: update all things
  apk: update_cache=yes upgrade=yes

- name: install pre dependencies
  apk: name={{ item }} state=present
  with_items: "{{ other_depend }}"

- name: Install Version Control
  apk: name={{ item }} state=present
  with_items: "{{ vcs }}"

- name: Build essentials
  apt: name=build-base state=present
