---

- name: update all things
  pacman: update_cache=yes upgrade=yes

- name: install pre dependencies
  pacman: name={{ item }} state=present
  with_items: "{{ other_depend }}"

- name: Install Version Control
  pacman: name={{ item }} state=present
  with_items: "{{ vcs }}"

- name: development installs
  pacman: name={{ item }} state=present
  with_items:
    - base-devel
    - abs
